FROM ubuntu
RUN apt update -y
RUN apt install software-properties-common -y
RUN apt install python3-pip -y
EXPOSE 8000/tcp
RUN mkdir /app

WORKDIR /app

COPY . .
RUN pip3 install -r requirements.txt
CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
